development:
  adapter: mysql
  database: explainpmt_dev
  username: root
  password: 
  hostname: localhost

# Do not set this db to the same as development or production.
test:
  adapter: mysql
  database: explainpmt_test
  username: root
  password: 
  hostname: localhost
