# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 1) do

  create_table "iterations", :force => true do |t|
    t.column "project_id", :integer
    t.column "start_date", :date
    t.column "length", :integer
    t.column "budget", :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "milestones", :force => true do |t|
    t.column "project_id", :integer
    t.column "date", :date
    t.column "name", :string
    t.column "description", :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "projects", :force => true do |t|
    t.column "name", :string
    t.column "description", :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  create_table "projects_users", :id => false, :force => true do |t|
    t.column "user_id", :integer
    t.column "project_id", :integer
  end

  create_table "stories", :force => true do |t|
    t.column "scid", :integer
    t.column "project_id", :integer
    t.column "iteration_id", :integer
    t.column "user_id", :integer
    t.column "title", :string
    t.column "points", :integer
    t.column "status", :integer
    t.column "priority", :integer
    t.column "risk", :integer
    t.column "description", :text
  end

  create_table "users", :force => true do |t|
    t.column "username", :string
    t.column "password", :string
    t.column "email", :string
    t.column "first_name", :string
    t.column "last_name", :string
    t.column "admin", :boolean
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

end
